#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.4.5
# In conjunction with Tcl version 8.6
#    Jan 28, 2015 11:19:48 PM
import sys
from ftplib import FTP

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import ftp_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('FTP_Grabber')
    root.geometry('424x164+564+150')
    w = FTP_Grabber (root)
    ftp_support.init(root, w)
    root.mainloop()

w = None
def create_FTP_Grabber(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('FTP_Grabber')
    w.geometry('424x164+564+150')
    w_win = FTP_Grabber (w)
    ftp_support.init(w, w_win, param)
    return w_win

def destroy_FTP_Grabber():
    global w
    w.destroy()
    w = None


class FTP_Grabber:
    def grab_file(self):
        """button's callback"""
        server = self.server_text.get()
        filepath = self.file_text.get()
        ftp = FTP(server)       # connect to host, default port
        ftp.login()             # user anonymous, passwd anonymous
        ftp.retrbinary('RETR %s' % filepath,
                       open(filepath.split("/")[-1], 'wb').write)
        
    
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.file_text = Entry(master)
        self.file_text.place(relx=0.19, rely=0.3, relheight=0.1, relwidth=0.76)
        self.file_text.configure(background="white")
        self.file_text.configure(disabledforeground="#a3a3a3")
        self.file_text.configure(font="TkFixedFont")
        self.file_text.configure(foreground="#000000")
        self.file_text.configure(highlightbackground="#d9d9d9")
        self.file_text.configure(highlightcolor="black")
        self.file_text.configure(insertbackground="black")
        self.file_text.configure(selectbackground="#c4c4c4")
        self.file_text.configure(selectforeground="black")
        self.file_text.insert(0, 'debian/README')

        self.Message1 = Message(master)
        self.Message1.place(relx=0.09, rely=0.3, relheight=0.14, relwidth=0.08)
        self.Message1.configure(background=_bgcolor)
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''File:''')
        self.Message1.configure(width=60)

        self.grab_button = Button(master)
        self.grab_button.place(relx=0.14, rely=0.55, height=24, width=36)
        self.grab_button.configure(activebackground="#d9d9d9")
        self.grab_button.configure(activeforeground="#000000")
        self.grab_button.configure(background=_bgcolor)
        self.grab_button.configure(disabledforeground="#a3a3a3")
        self.grab_button.configure(foreground="#000000")
        self.grab_button.configure(highlightbackground="#d9d9d9")
        self.grab_button.configure(highlightcolor="black")
        self.grab_button.configure(pady="0")
        self.grab_button.configure(text='''Grab''')

        self.server_text = Entry(master)
        self.server_text.place(relx=0.19, rely=0.12, relheight=0.1
                , relwidth=0.76)
        self.server_text.configure(background="white")
        self.server_text.configure(disabledforeground="#a3a3a3")
        self.server_text.configure(font="TkFixedFont")
        self.server_text.configure(foreground="#000000")
        self.server_text.configure(highlightbackground="#d9d9d9")
        self.server_text.configure(highlightcolor="black")
        self.server_text.configure(insertbackground="black")
        self.server_text.configure(selectbackground="#c4c4c4")
        self.server_text.configure(selectforeground="black")
        self.server_text.insert(0, 'ftp.debian.org')

        self.Message2 = Message(master)
        self.Message2.place(relx=0.07, rely=0.12, relheight=0.14, relwidth=0.12)
        self.Message2.configure(background=_bgcolor)
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''Server:''')
        self.Message2.configure(width=60)

        self.grab_button.configure(command=self.grab_file)



if __name__ == '__main__':
    vp_start_gui()



