#############################################################################
# Generated by PAGE version 4.4.5
# in conjunction with Tcl version 8.6
#    Jan 28, 2015 10:49:59 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 424x164+564+150; update
    wm maxsize $top 1370 750
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "FTP Grabber"
    vTcl:DefineAlias "$top" "ftp_grabber_window" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Entry -background #d9d9d9
    ttk::style configure Entry -foreground #000000
    ttk::style configure Entry -font TkDefaultFont
    entry $top.ent37 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent37" "file_text" vTcl:WidgetProc "ftp_grabber_window" 1
    message $top.mes38 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text File: \
        -width 60 
    vTcl:DefineAlias "$top.mes38" "Message1" vTcl:WidgetProc "ftp_grabber_window" 1
    button $top.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Grab 
    vTcl:DefineAlias "$top.but39" "grab_button" vTcl:WidgetProc "ftp_grabber_window" 1
    entry $top.ent36 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable 'ftp.debian.org' 
    vTcl:DefineAlias "$top.ent36" "server_text" vTcl:WidgetProc "ftp_grabber_window" 1
    message $top.mes37 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Server: \
        -width 60 
    vTcl:DefineAlias "$top.mes37" "Message2" vTcl:WidgetProc "ftp_grabber_window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent37 \
        -in $top -x 80 -y 50 -width 324 -height 17 -anchor nw \
        -bordermode ignore 
    place $top.mes38 \
        -in $top -x 40 -y 50 -anchor nw -bordermode ignore 
    place $top.but39 \
        -in $top -x 60 -y 90 -anchor nw -bordermode ignore 
    place $top.ent36 \
        -in $top -x 80 -y 20 -width 324 -height 17 -anchor nw \
        -bordermode ignore 
    place $top.mes37 \
        -in $top -x 30 -y 20 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

